const { jsPDF } = require("jspdf");
const fs = require("fs");

const doc = new jsPDF();
const outputPath = "C:/Users/hp/AndroidStudioProjects/BARR/.artifacts/666af74a-c582-4c48-8372-9335475857a0/Apex_Titan_Architecture.pdf";

// Title
doc.setFontSize(22);
doc.setTextColor(245, 160, 0); // Apex Primary
doc.text("APEX TITAN SYSTEM ARCHITECTURE", 20, 20);

doc.setFontSize(12);
doc.setTextColor(15, 23, 42); // Apex Foreground
doc.text("Technical Documentation & Integration Blueprint", 20, 30);
doc.line(20, 35, 190, 35);

// Section: Titan Node (Android)
doc.setFontSize(16);
doc.text("1. Titan Node (Android Application)", 20, 50);
doc.setFontSize(10);
let y = 60;
const androidPoints = [
    "- MainActivity: The Secure Hub. Manages Biometric Shield (Fingerprint/Face) and the Hybrid Bridge.",
    "- TitanBridge: A high-velocity JavaScript Interface connecting Native Hardware to Web UI.",
    "- Edge AI Scanner: ML Kit powered engine for Barcode Scanning, AI Triage, and Shelf Auditing.",
    "- LocationService: Persistent foreground synchronization for real-time node tracking.",
    "- Supabase Integration: Encrypted storage for offline drops and REST API configuration sync."
];
androidPoints.forEach(p => {
    doc.text(p, 25, y);
    y += 7;
});

// Section: Apex Command Hub (Web)
y += 10;
doc.setFontSize(16);
doc.text("2. Apex Command Hub (Next.js / Web)", 20, y);
doc.setFontSize(10);
y += 10;
const webPoints = [
    "- Intelligence Hub: Real-time PostgreSQL signal monitoring and tactical analytics visualization.",
    "- Mission Control: Centralized logistics management for dispatching orders and tracking nodes.",
    "- Framework: Built with Next.js 15, optimized for deployment on Render, using Framer Motion for UI.",
    "- Deployment: Continuous integration via GitHub 'tech' remote."
];
webPoints.forEach(p => {
    doc.text(p, 25, y);
    y += 7;
});

// Section: Interconnectivity
y += 10;
doc.setFontSize(16);
doc.text("3. System Interconnectivity & Data Flow", 20, y);
doc.setFontSize(10);
y += 10;
const flowPoints = [
    "- Native-to-Web: Titan Node injects 'TitanNode' object into WebView for immediate hardware access.",
    "- Web-to-Native: The Dashboard triggers evaluateJavascript() to sync scanning results back to the UI.",
    "- Cloud Synchronization: Both platforms share a unified Supabase backend for real-time mission data.",
    "- Security Handover: Dynamic QR generation enables encrypted physical-to-digital rider validation."
];
flowPoints.forEach(p => {
    doc.text(p, 25, y);
    y += 7;
});

// Footer
doc.setFontSize(8);
doc.setTextColor(150, 150, 150);
doc.text("Generated by Apex OS Documentation Engine | 2026", 20, 280);

const data = doc.output();
fs.writeFileSync(outputPath, data, 'binary');
console.log("PDF successfully generated at: " + outputPath);
