-- APEX STORES: AFFILIATE ECONOMY SCHEMA

-- 1. Affiliate Profiles
CREATE TABLE IF NOT EXISTS public.affiliate_profiles (
    user_id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
    promo_name TEXT UNIQUE NOT NULL,
    social_handles JSONB DEFAULT '{}'::JSONB,
    tier TEXT DEFAULT 'Starter', -- Starter, Rising, Pro, Elite
    status TEXT DEFAULT 'Pending', -- Pending, Active, Suspended
    total_clicks INTEGER DEFAULT 0,
    conversion_rate NUMERIC DEFAULT 0.0,
    bio TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 2. Commission Configuration
CREATE TABLE IF NOT EXISTS public.affiliate_commissions (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    level TEXT NOT NULL, -- 'GLOBAL', 'CATEGORY', 'PRODUCT'
    target_id TEXT, -- Category name or Product ID
    rate_percent NUMERIC NOT NULL,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 3. Affiliate Wallets
CREATE TABLE IF NOT EXISTS public.affiliate_wallets (
    user_id UUID PRIMARY KEY REFERENCES public.affiliate_profiles(user_id) ON DELETE CASCADE,
    balance_available NUMERIC DEFAULT 0.0,
    balance_pending NUMERIC DEFAULT 0.0,
    lifetime_earned NUMERIC DEFAULT 0.0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 4. Withdrawals / Payouts
CREATE TABLE IF NOT EXISTS public.affiliate_withdrawals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES public.affiliate_profiles(user_id),
    amount NUMERIC NOT NULL,
    method TEXT DEFAULT 'M-Pesa',
    status TEXT DEFAULT 'Requested', -- Requested, Processing, Paid, Rejected
    payout_ref TEXT,
    processed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 5. Click Tracking
CREATE TABLE IF NOT EXISTS public.affiliate_clicks (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    affiliate_id UUID REFERENCES public.affiliate_profiles(user_id),
    product_id BIGINT REFERENCES public.products(id),
    ip_address TEXT,
    user_agent TEXT,
    referer TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 6. Referral Orders (Attribution)
CREATE TABLE IF NOT EXISTS public.affiliate_referrals (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
    affiliate_id UUID REFERENCES public.affiliate_profiles(user_id),
    commission_amount NUMERIC NOT NULL,
    status TEXT DEFAULT 'Pending', -- Pending, Approved, Cancelled
    approved_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 7. Add columns to Orders for attribution
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS affiliate_id UUID REFERENCES public.affiliate_profiles(user_id);

-- 8. Enable RLS
ALTER TABLE public.affiliate_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.affiliate_commissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.affiliate_wallets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.affiliate_withdrawals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.affiliate_clicks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.affiliate_referrals ENABLE ROW LEVEL SECURITY;

-- 9. Basic Policies
CREATE POLICY "Users see own affiliate profile" ON public.affiliate_profiles FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users see own wallet" ON public.affiliate_wallets FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users manage own withdrawals" ON public.affiliate_withdrawals FOR ALL USING (auth.uid() = user_id);

-- 10. RPC for Commission Calculation
CREATE OR REPLACE FUNCTION public.calculate_affiliate_commission(order_id_input BIGINT)
RETURNS VOID AS $$
DECLARE
    order_total NUMERIC;
    aff_id UUID;
    commission_rate NUMERIC;
    final_commission NUMERIC;
BEGIN
    -- 1. Get Order Details
    SELECT total_price, affiliate_id INTO order_total, aff_id FROM public.orders WHERE id = order_id_input;

    IF aff_id IS NULL THEN RETURN; END IF;

    -- 2. Get Global Rate (default 5%)
    SELECT rate_percent INTO commission_rate FROM public.affiliate_commissions WHERE level = 'GLOBAL' LIMIT 1;
    IF commission_rate IS NULL THEN commission_rate := 5.0; END IF;

    -- 3. Calculate
    final_commission := order_total * (commission_rate / 100);

    -- 4. Record Referral
    INSERT INTO public.affiliate_referrals (order_id, affiliate_id, commission_amount, status)
    VALUES (order_id_input, aff_id, final_commission, 'Pending');

    -- 5. Update Wallet (Pending)
    UPDATE public.affiliate_wallets
    SET balance_pending = balance_pending + final_commission
    WHERE user_id = aff_id;

END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
