-- APEX STORES: AFFILIATE COMMAND CENTER EXTENSION

-- 1. Extend Affiliate Profiles
ALTER TABLE public.affiliate_profiles ADD COLUMN IF NOT EXISTS business_name TEXT;
ALTER TABLE public.affiliate_profiles ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE public.affiliate_profiles ADD COLUMN IF NOT EXISTS country TEXT DEFAULT 'Kenya';
ALTER TABLE public.affiliate_profiles ADD COLUMN IF NOT EXISTS language TEXT DEFAULT 'English';
ALTER TABLE public.affiliate_profiles ADD COLUMN IF NOT EXISTS verification_status JSONB DEFAULT '{"phone": false, "email": false, "account": false, "payment": false, "agreement": false}'::JSONB;
ALTER TABLE public.affiliate_profiles ADD COLUMN IF NOT EXISTS last_active_at TIMESTAMP WITH TIME ZONE DEFAULT now();
ALTER TABLE public.affiliate_profiles ADD COLUMN IF NOT EXISTS readable_id TEXT UNIQUE;

-- 2. Affiliate Leads Table
CREATE TABLE IF NOT EXISTS public.affiliate_leads (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    affiliate_id UUID REFERENCES public.affiliate_profiles(user_id) ON DELETE CASCADE,
    customer_name TEXT NOT NULL,
    customer_phone TEXT NOT NULL,
    interested_product_id BIGINT REFERENCES public.products(id),
    budget NUMERIC,
    notes TEXT,
    status TEXT DEFAULT 'New', -- New, Contacted, Negotiating, Paid, Lost
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 3. Affiliate Assets (Marketing Materials)
CREATE TABLE IF NOT EXISTS public.affiliate_assets (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    type TEXT NOT NULL, -- 'Image', 'Video', 'Post', 'Script'
    category TEXT NOT NULL, -- 'WhatsApp', 'Instagram', 'TikTok'
    file_url TEXT,
    content TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 4. Affiliate Announcements
CREATE TABLE IF NOT EXISTS public.affiliate_announcements (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    priority TEXT DEFAULT 'Normal', -- Normal, High, Urgent
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 5. Enable RLS
ALTER TABLE public.affiliate_leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.affiliate_assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.affiliate_announcements ENABLE ROW LEVEL SECURITY;

-- 6. Policies
CREATE POLICY "Affiliates see own leads" ON public.affiliate_leads FOR SELECT USING (auth.uid() = affiliate_id);
CREATE POLICY "Affiliates create leads" ON public.affiliate_leads FOR INSERT WITH CHECK (auth.uid() = affiliate_id);
CREATE POLICY "Public see affiliate assets" ON public.affiliate_assets FOR SELECT USING (true);
CREATE POLICY "Public see affiliate announcements" ON public.affiliate_announcements FOR SELECT USING (true);

-- 7. Trigger to generate Readable ID (e.g. APX-00001)
CREATE OR REPLACE FUNCTION public.generate_affiliate_readable_id()
RETURNS trigger AS $$
DECLARE
    next_val BIGINT;
BEGIN
    SELECT count(*) + 1 INTO next_val FROM public.affiliate_profiles;
    NEW.readable_id := 'APX-' || LPAD(next_val::text, 5, '0');
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tr_generate_aff_id ON public.affiliate_profiles;
CREATE TRIGGER tr_generate_aff_id
    BEFORE INSERT ON public.affiliate_profiles
    FOR EACH ROW EXECUTE PROCEDURE public.generate_affiliate_readable_id();
