-- ==========================================
-- APEX OS: MASTER SCHEMA FIX
-- Use this script to resolve "relation does not exist" errors.
-- ==========================================

-- 1. BASE ORDERS TABLE (Required by many other components)
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    rider_phone TEXT,
    customer_phone TEXT,
    product_id BIGINT,
    quantity INTEGER DEFAULT 1,
    total_price NUMERIC,
    delivery_cost NUMERIC DEFAULT 0,
    status TEXT DEFAULT 'Pending', -- Pending, Paid, Processing, Dispatched, Delivered, Cancelled
    payment_method TEXT DEFAULT 'M-PESA',
    delivery_address TEXT,
    dispatched_at TIMESTAMPTZ,
    delivered_at TIMESTAMPTZ,
    rider_rating INTEGER CHECK (rider_rating >= 1 AND rider_rating <= 5),
    rider_feedback TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 2. ENHANCE RIDER STATUS TABLE (Fix for onboarding)
ALTER TABLE public.rider_status
ADD COLUMN IF NOT EXISTS id_number TEXT,
ADD COLUMN IF NOT EXISTS license_number TEXT,
ADD COLUMN IF NOT EXISTS plate_number TEXT,
ADD COLUMN IF NOT EXISTS biometric_key TEXT,
ADD COLUMN IF NOT EXISTS id_photo_front_url TEXT,
ADD COLUMN IF NOT EXISTS id_photo_back_url TEXT,
ADD COLUMN IF NOT EXISTS license_photo_url TEXT,
ADD COLUMN IF NOT EXISTS avg_delivery_speed INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS last_battery_sync TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS total_missions_completed INTEGER DEFAULT 0;

-- 3. TACTICAL PERFORMANCE TRIGGER
CREATE OR REPLACE FUNCTION calculate_rider_speed()
RETURNS TRIGGER AS $$
DECLARE
    order_speed INTEGER;
    current_avg INTEGER;
    total_count INTEGER;
BEGIN
    IF NEW.status = 'Delivered' AND OLD.status != 'Delivered' AND NEW.dispatched_at IS NOT NULL AND NEW.delivered_at IS NOT NULL THEN
        -- Calculate minutes for this delivery
        order_speed := EXTRACT(EPOCH FROM (NEW.delivered_at - NEW.dispatched_at)) / 60;

        -- Update rider stats
        SELECT avg_delivery_speed, total_missions_completed
        INTO current_avg, total_count
        FROM public.rider_status
        WHERE rider_phone = NEW.rider_phone;

        IF total_count IS NULL THEN total_count := 0; END IF;
        IF current_avg IS NULL THEN current_avg := 0; END IF;

        -- New Average
        UPDATE public.rider_status
        SET
            avg_delivery_speed = ((current_avg * total_count) + order_speed) / (total_count + 1),
            total_missions_completed = total_count + 1,
            updated_at = NOW()
        WHERE rider_phone = NEW.rider_phone;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_calculate_rider_speed ON public.orders;
CREATE TRIGGER trigger_calculate_rider_speed
AFTER UPDATE ON public.orders
FOR EACH ROW
EXECUTE FUNCTION calculate_rider_speed();
