-- ==========================================
-- APEX OS: CUSTOMER INTELLIGENCE SCHEMA 🧠👁️🛡️
-- ==========================================

-- 1. VISITOR IDENTITY (Persistent ID resolution)
CREATE TABLE IF NOT EXISTS public.visitor_identity (
    visitor_id TEXT PRIMARY KEY, -- Browser-based UUID
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL, -- Resolved user if logged in
    first_seen TIMESTAMPTZ DEFAULT now(),
    last_seen TIMESTAMPTZ DEFAULT now(),
    conversion_count INTEGER DEFAULT 0,
    total_spend NUMERIC DEFAULT 0.0,
    acquisition_source TEXT, -- e.g. Instagram
    acquisition_campaign TEXT -- e.g. August_Sale
);

-- 2. USER SESSIONS (Tactical Journey Records)
CREATE TABLE IF NOT EXISTS public.user_sessions (
    session_id TEXT PRIMARY KEY,
    visitor_id TEXT NOT NULL REFERENCES public.visitor_identity(visitor_id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    utm_source TEXT,
    utm_medium TEXT,
    utm_campaign TEXT,
    utm_content TEXT,
    device_type TEXT, -- Mobile, Desktop, Tablet
    browser TEXT,
    os TEXT,
    ip_address TEXT,
    location_city TEXT,
    entry_url TEXT,
    exit_url TEXT,
    dwell_time_seconds INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT now(),
    ended_at TIMESTAMPTZ
);

-- 3. ENHANCED USER SIGNALS (The Event Stream)
CREATE TABLE IF NOT EXISTS public.user_signals (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    session_id TEXT NOT NULL,
    visitor_id TEXT REFERENCES public.visitor_identity(visitor_id) ON DELETE SET NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    event_type TEXT NOT NULL, -- VIEW, CLICK, SCROLL, DWELL, QUICK_VIEW, SEARCH, ADD_TO_BAG, CHECKOUT_START
    target TEXT, -- Section ID, Product ID, or Element name
    metadata JSONB DEFAULT '{}'::jsonb,
    url TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 4. SEARCH INTELLIGENCE (Demand Capture)
CREATE TABLE IF NOT EXISTS public.search_intelligence (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    session_id TEXT REFERENCES public.user_sessions(session_id) ON DELETE CASCADE,
    query TEXT NOT NULL,
    results_count INTEGER DEFAULT 0,
    clicked_product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    is_success BOOLEAN DEFAULT false,
    category_hint TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 5. PERFORMANCE INDEXING (War Room Speed)
CREATE INDEX IF NOT EXISTS idx_sessions_visitor ON public.user_sessions(visitor_id);
CREATE INDEX IF NOT EXISTS idx_sessions_created ON public.user_sessions(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_signals_visitor ON public.user_signals(visitor_id);
CREATE INDEX IF NOT EXISTS idx_search_query ON public.search_intelligence(query);
CREATE INDEX IF NOT EXISTS idx_search_success ON public.search_intelligence(is_success) WHERE is_success = false;

-- 6. SECURITY SHIELD: RLS
ALTER TABLE public.visitor_identity ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.search_intelligence ENABLE ROW LEVEL SECURITY;

-- Allow anonymous inserts for behavioral logging
CREATE POLICY "Public record identity" ON public.visitor_identity FOR INSERT WITH CHECK (true);
CREATE POLICY "Public record session" ON public.user_sessions FOR INSERT WITH CHECK (true);
CREATE POLICY "Public record search" ON public.search_intelligence FOR INSERT WITH CHECK (true);

-- Restricted access for select
CREATE POLICY "Admin view identity" ON public.visitor_identity FOR SELECT USING (EXISTS (SELECT 1 FROM public.staff WHERE id = auth.uid() AND role IN ('owner', 'admin')));
CREATE POLICY "Admin view session" ON public.user_sessions FOR SELECT USING (EXISTS (SELECT 1 FROM public.staff WHERE id = auth.uid() AND role IN ('owner', 'admin')));
CREATE POLICY "Admin view search" ON public.search_intelligence FOR SELECT USING (EXISTS (SELECT 1 FROM public.staff WHERE id = auth.uid() AND role IN ('owner', 'admin')));

-- 7. TACTICAL FUNCTIONS
CREATE OR REPLACE FUNCTION public.increment_session_dwell(sid TEXT, inc INTEGER)
RETURNS VOID AS $$
BEGIN
    UPDATE public.user_sessions
    SET dwell_time_seconds = dwell_time_seconds + inc,
        ended_at = now()
    WHERE session_id = sid;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- FORCE RELOAD SCHEMA
NOTIFY pgrst, 'reload schema';
