-- ==========================================
-- APEX OS: SOCIAL HUB & PUBLISHER 🚀📱💬
-- ==========================================

-- 1. SOCIAL INTEGRATIONS (Token Store)
CREATE TABLE IF NOT EXISTS public.social_integrations (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    platform TEXT NOT NULL UNIQUE, -- facebook, instagram, tiktok, whatsapp, gmail
    account_name TEXT,
    account_id TEXT,
    access_token TEXT,
    refresh_token TEXT,
    expires_at TIMESTAMPTZ,
    is_connected BOOLEAN DEFAULT true,
    metadata JSONB DEFAULT '{}'::jsonb,
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 2. SOCIAL CAMPAIGNS (Master Content)
CREATE TABLE IF NOT EXISTS public.social_campaigns (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    description TEXT,
    media_url TEXT,
    media_type TEXT, -- image, video
    target_url TEXT,
    created_by TEXT, -- staff email
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. CAMPAIGN POSTS (Platform Delivery)
CREATE TABLE IF NOT EXISTS public.campaign_posts (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    campaign_id BIGINT REFERENCES public.social_campaigns(id) ON DELETE CASCADE,
    platform TEXT NOT NULL,
    external_post_id TEXT,
    status TEXT DEFAULT 'QUEUED', -- QUEUED, PROCESSING, PUBLISHED, FAILED
    error_message TEXT,
    platform_caption TEXT,
    published_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 4. SOCIAL ANALYTICS (Reach & ROI)
CREATE TABLE IF NOT EXISTS public.social_analytics (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    post_id BIGINT REFERENCES public.campaign_posts(id) ON DELETE CASCADE,
    platform TEXT NOT NULL,
    reach INTEGER DEFAULT 0,
    engagement INTEGER DEFAULT 0,
    clicks INTEGER DEFAULT 0,
    leads INTEGER DEFAULT 0,
    orders INTEGER DEFAULT 0,
    revenue NUMERIC DEFAULT 0.0,
    recorded_at TIMESTAMPTZ DEFAULT now()
);

-- 5. PERFORMANCE INDEXING
CREATE INDEX IF NOT EXISTS idx_posts_campaign ON public.campaign_posts(campaign_id);
CREATE INDEX IF NOT EXISTS idx_analytics_post ON public.social_analytics(post_id);
CREATE INDEX IF NOT EXISTS idx_analytics_platform ON public.social_analytics(platform);

-- 6. SECURITY SHIELD: RLS
ALTER TABLE public.social_integrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.social_campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campaign_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.social_analytics ENABLE ROW LEVEL SECURITY;

-- Only owners and authorized admins can manage integrations
CREATE POLICY "Admins manage social integrations" ON public.social_integrations
USING (EXISTS (SELECT 1 FROM public.staff WHERE id = auth.uid() AND role IN ('owner', 'admin')));

CREATE POLICY "Admins manage social campaigns" ON public.social_campaigns
USING (EXISTS (SELECT 1 FROM public.staff WHERE id = auth.uid() AND role IN ('owner', 'admin', 'staff')));

CREATE POLICY "Admins view social analytics" ON public.social_analytics
USING (EXISTS (SELECT 1 FROM public.staff WHERE id = auth.uid() AND role IN ('owner', 'admin', 'staff')));

-- FORCE RELOAD SCHEMA
NOTIFY pgrst, 'reload schema';
