-- ==========================================
-- APEX OS: SIGNAL INTELLIGENCE CORE 🧠👁️
-- ==========================================

-- 1. BEHAVIORAL SIGNALS TABLE
CREATE TABLE IF NOT EXISTS public.user_signals (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    session_id TEXT NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    event_type TEXT NOT NULL, -- VIEW, CLICK, SCROLL, DWELL, QUICK_VIEW
    target TEXT, -- Section ID, Product ID, or Element name
    metadata JSONB DEFAULT '{}'::jsonb, -- duration_ms, scroll_depth, etc.
    url TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. PERFORMANCE INDEXING
CREATE INDEX IF NOT EXISTS idx_signals_session ON public.user_signals(session_id);
CREATE INDEX IF NOT EXISTS idx_signals_event ON public.user_signals(event_type);
CREATE INDEX IF NOT EXISTS idx_signals_target ON public.user_signals(target);
CREATE INDEX IF NOT EXISTS idx_signals_created ON public.user_signals(created_at DESC);

-- 3. SECURITY SHIELD: RLS
ALTER TABLE public.user_signals ENABLE ROW LEVEL SECURITY;

-- Allow anonymous insertion (Rate limiting is handled at the API/Load balancer level)
DROP POLICY IF EXISTS "Public can record signals" ON public.user_signals;
CREATE POLICY "Public can record signals" ON public.user_signals FOR INSERT
WITH CHECK (true);

-- Only admins/owners can view the raw signals
DROP POLICY IF EXISTS "Admins can view signals" ON public.user_signals;
CREATE POLICY "Admins can view signals" ON public.user_signals FOR SELECT
USING (
    EXISTS (
        SELECT 1 FROM public.staff
        WHERE id = auth.uid()
        AND role IN ('owner', 'admin')
    )
);

-- FORCE RELOAD SCHEMA
NOTIFY pgrst, 'reload schema';
