-- APEX OS: ORDER HEADER REFACTOR
-- Decouples orders from single items to support multi-item fulfillment.

-- 1. HEADERIZE ORDERS TABLE
ALTER TABLE public.orders ALTER COLUMN product_id DROP NOT NULL;
ALTER TABLE public.orders ALTER COLUMN quantity DROP NOT NULL;
ALTER TABLE public.orders ALTER COLUMN unit_price DROP NOT NULL;
ALTER TABLE public.orders ALTER COLUMN unit_cost DROP NOT NULL;

-- 2. ENHANCED ORDER ITEMS (Granular tracking)
CREATE TABLE IF NOT EXISTS public.order_items (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    inventory_unit_id BIGINT REFERENCES public.inventory_units(id) ON DELETE SET NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    unit_price NUMERIC NOT NULL,
    unit_cost NUMERIC NOT NULL,
    size TEXT DEFAULT 'Standard',
    status TEXT DEFAULT 'Pending',
    supplier_id BIGINT REFERENCES public.suppliers(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 3. AUTOMATED HEADER UPDATES
-- Ensures the order total always matches the sum of items + shipping
CREATE OR REPLACE FUNCTION public.sync_order_header_totals()
RETURNS trigger AS $$
BEGIN
    UPDATE public.orders
    SET total_price = (
        SELECT COALESCE(SUM(unit_price * quantity), 0)
        FROM public.order_items
        WHERE order_id = COALESCE(NEW.order_id, OLD.order_id)
    ) + (SELECT delivery_cost FROM public.orders WHERE id = COALESCE(NEW.order_id, OLD.order_id))
    WHERE id = COALESCE(NEW.order_id, OLD.order_id);

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tr_sync_order_totals ON public.order_items;
CREATE TRIGGER tr_sync_order_totals
    AFTER INSERT OR UPDATE OR DELETE ON public.order_items
    FOR EACH ROW EXECUTE PROCEDURE public.sync_order_header_totals();
