-- TITAN HUB: MASTER SYSTEM SYNC
-- Consolidates all tables, relationships, and RLS policies for a 100% linked ecosystem.
-- UPDATED: Added Gamification, Streaks, and Daily Rewards support.

-- 1. PRODUCTS
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  price NUMERIC NOT NULL,
  old_price NUMERIC,
  cost_price NUMERIC DEFAULT 0,
  description TEXT,
  image_url TEXT,
  images TEXT[] DEFAULT ARRAY[]::TEXT[],
  video_url TEXT,
  category TEXT DEFAULT 'electronics',
  sizes TEXT[] DEFAULT ARRAY['Standard'],
  stock INT DEFAULT 0,
  variant_stock JSONB DEFAULT '{}'::JSONB,
  tech_specs JSONB DEFAULT '{}'::JSONB,
  is_featured BOOLEAN DEFAULT false,
  featured_rank INT DEFAULT 99,
  is_new BOOLEAN DEFAULT true,
  sale_end_date TIMESTAMP WITH TIME ZONE,
  rating NUMERIC DEFAULT 5.0,
  status TEXT DEFAULT 'Live', -- NEW: Live, Pending, Rejected
  supplier_id BIGINT, -- NEW: Link to supplier
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 2. PROFILES (Customers)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT,
  full_name TEXT,
  phone_number TEXT UNIQUE,
  address TEXT,
  latitude NUMERIC,
  longitude NUMERIC,
  birth_date DATE,
  referral_code TEXT UNIQUE,
  referral_clicks INTEGER DEFAULT 0,
  loyalty_points INTEGER DEFAULT 0,
  total_commission_earned NUMERIC DEFAULT 0,
  status_flag TEXT DEFAULT 'Active',
  current_streak INTEGER DEFAULT 0, -- NEW: Streak tracking
  last_streak_update TIMESTAMP WITH TIME ZONE, -- NEW: Streak tracking
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 3. ORDERS
CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  session_id TEXT,
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  customer_email TEXT,
  product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
  quantity INT NOT NULL DEFAULT 1,
  size TEXT DEFAULT 'Standard',
  unit_price NUMERIC,
  unit_cost NUMERIC,
  total_price NUMERIC NOT NULL,
  status TEXT DEFAULT 'Pending',
  payment_method TEXT DEFAULT 'M-Pesa',
  checkout_request_id TEXT,
  payment_verified_at TIMESTAMP WITH TIME ZONE,
  note TEXT,
  referred_by_code TEXT,
  rider_name TEXT,
  rider_phone TEXT,
  captured_by TEXT DEFAULT 'system',
  latitude NUMERIC,
  longitude NUMERIC,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 4. RIDER STATUS & LOGISTICS
CREATE TABLE IF NOT EXISTS public.rider_status (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    rider_name TEXT NOT NULL,
    rider_phone TEXT UNIQUE NOT NULL,
    vehicle_type TEXT DEFAULT 'Motorbike',
    vehicle_reg TEXT,
    pin TEXT DEFAULT '1234',
    current_location TEXT,
    status TEXT DEFAULT 'Offline',
    battery_level INTEGER DEFAULT 100,
    total_deliveries INTEGER DEFAULT 0,
    rating DECIMAL DEFAULT 5.0,
    area_zone TEXT DEFAULT 'Nairobi',
    max_deliveries INTEGER DEFAULT 10,
    weekly_salary NUMERIC DEFAULT 0,
    health_score INTEGER DEFAULT 100,
    current_tier TEXT DEFAULT 'Bronze',
    acceptance_rate INTEGER DEFAULT 100,
    online_since TIMESTAMP WITH TIME ZONE,
    biometric_key JSONB,
    verification_status TEXT DEFAULT 'Pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() -- NEW: For stall detection
);

-- Trigger to auto-update updated_at for rider_status
CREATE OR REPLACE FUNCTION update_rider_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tr_update_rider_timestamp ON public.rider_status;
CREATE TRIGGER tr_update_rider_timestamp
    BEFORE UPDATE ON public.rider_status
    FOR EACH ROW EXECUTE PROCEDURE update_rider_timestamp();

CREATE TABLE IF NOT EXISTS public.rider_wallets (
    rider_phone TEXT PRIMARY KEY REFERENCES public.rider_status(rider_phone) ON DELETE CASCADE,
    balance NUMERIC DEFAULT 0,
    total_earned NUMERIC DEFAULT 0,
    last_payout TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 5. ABANDONED & ACTIVE TRAFFIC
CREATE TABLE IF NOT EXISTS public.abandoned_carts (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  customer_name TEXT,
  customer_phone TEXT UNIQUE,
  customer_email TEXT,
  cart_items JSONB,
  total_price NUMERIC,
  session_id TEXT,
  recovery_status TEXT DEFAULT 'Waiting',
  recovery_sent_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.active_visitors (
  session_id TEXT PRIMARY KEY,
  customer_name TEXT,
  current_page TEXT,
  last_active_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  cart_value NUMERIC DEFAULT 0,
  status TEXT DEFAULT 'Browsing'
);

-- 6. ENTERPRISE: STAFF & AUDIT
CREATE TABLE IF NOT EXISTS public.staff (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT UNIQUE NOT NULL,
  role TEXT DEFAULT 'staff',
  pin TEXT,
  supplier_id BIGINT, -- NEW: Link to specific supply partner
  can_view_revenue BOOLEAN DEFAULT false,
  can_manage_inventory BOOLEAN DEFAULT true,
  can_manage_orders BOOLEAN DEFAULT true,
  can_delete_items BOOLEAN DEFAULT false,
  can_manage_blog BOOLEAN DEFAULT false,
  can_manage_affiliates BOOLEAN DEFAULT false,
  can_manage_customer_care BOOLEAN DEFAULT false,
  can_manage_broadcast BOOLEAN DEFAULT false,
  can_manage_settings BOOLEAN DEFAULT false,
  can_manage_media BOOLEAN DEFAULT false,
  can_view_sensitive_rider_data BOOLEAN DEFAULT false,
  can_view_audit_logs BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    staff_email TEXT,
    action TEXT NOT NULL,
    details JSONB,
    ip_address TEXT,
    device_info TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 7. SETTINGS & SYSTEM
CREATE TABLE IF NOT EXISTS public.settings (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL,
    is_published BOOLEAN DEFAULT true,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 8. REVIEWS & MESSAGES
CREATE TABLE IF NOT EXISTS public.reviews (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
  customer_name TEXT NOT NULL,
  customer_phone TEXT,
  rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment TEXT,
  photo_urls TEXT[] DEFAULT ARRAY[]::TEXT[],
  is_verified_owner BOOLEAN DEFAULT false,
  is_hidden BOOLEAN DEFAULT false,
  admin_response TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.messages (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL, -- NEW: Link to account
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  subject TEXT DEFAULT 'In-App Support Ticket',
  message TEXT NOT NULL,
  status TEXT DEFAULT 'New',
  admin_response TEXT, -- NEW: Staff reply content
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 9. REWARDS & GAMIFICATION
CREATE TABLE IF NOT EXISTS public.loyalty_ledger (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    amount INTEGER NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.user_missions (
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    mission_type TEXT NOT NULL,
    progress INTEGER DEFAULT 0,
    is_completed BOOLEAN DEFAULT false,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    PRIMARY KEY (user_id, mission_type)
);

CREATE TABLE IF NOT EXISTS public.daily_rewards_log (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    reward_type TEXT NOT NULL, -- 'spin' or 'box'
    reward_label TEXT NOT NULL,
    reward_value INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 10. INDEXES FOR ELITE SPEED
CREATE INDEX IF NOT EXISTS idx_orders_customer_phone ON public.orders(customer_phone);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON public.orders(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_products_category ON public.products(category);
CREATE INDEX IF NOT EXISTS idx_reviews_customer_phone ON public.reviews(customer_phone);

-- 11. ROW LEVEL SECURITY (RLS) POLICIES
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rider_status ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_missions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_rewards_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.loyalty_ledger ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY; -- NEW

-- Product Policies
DROP POLICY IF EXISTS "Public Read Products" ON public.products;
CREATE POLICY "Public Read Products" ON public.products FOR SELECT USING (true);

-- Profile Policies
DROP POLICY IF EXISTS "Users view own profile" ON public.profiles;
CREATE POLICY "Users view own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);
DROP POLICY IF EXISTS "Users update own profile" ON public.profiles;
CREATE POLICY "Users update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Order Policies
DROP POLICY IF EXISTS "Users see own orders" ON public.orders;
CREATE POLICY "Users see own orders" ON public.orders FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Public Insert Orders" ON public.orders;
CREATE POLICY "Public Insert Orders" ON public.orders FOR INSERT WITH CHECK (true);

-- Gamification Policies
DROP POLICY IF EXISTS "Users see own missions" ON public.user_missions;
CREATE POLICY "Users see own missions" ON public.user_missions FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users see own rewards log" ON public.daily_rewards_log;
CREATE POLICY "Users see own rewards log" ON public.daily_rewards_log FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users see own ledger" ON public.loyalty_ledger;
CREATE POLICY "Users see own ledger" ON public.loyalty_ledger FOR SELECT USING (auth.uid() = profile_id);

-- Message Policies (Support Tickets)
DROP POLICY IF EXISTS "Public Insert Messages" ON public.messages;
CREATE POLICY "Public Insert Messages" ON public.messages FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Users see own messages" ON public.messages;
CREATE POLICY "Users see own messages" ON public.messages FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Admins manage all messages" ON public.messages;
CREATE POLICY "Admins manage all messages" ON public.messages FOR ALL TO authenticated USING (true);

-- Master Admin / Staff Bypass
DROP POLICY IF EXISTS "Admins have full access" ON public.products;
CREATE POLICY "Admins have full access" ON public.products FOR ALL TO authenticated USING (true);
DROP POLICY IF EXISTS "Admins see all orders" ON public.orders;
CREATE POLICY "Admins see all orders" ON public.orders FOR SELECT TO authenticated USING (true);

-- 12. TACTICAL FUNCTIONS (RPCs)

-- Credit Rider Wallet securely
CREATE OR REPLACE FUNCTION public.credit_rider_wallet(phone_input TEXT, amount_input NUMERIC)
RETURNS VOID AS $$
BEGIN
    INSERT INTO public.rider_wallets (rider_phone, balance, total_earned)
    VALUES (phone_input, amount_input, amount_input)
    ON CONFLICT (rider_phone)
    DO UPDATE SET
        balance = public.rider_wallets.balance + amount_input,
        total_earned = public.rider_wallets.total_earned + amount_input,
        updated_at = NOW();
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Get User ID by Email (For Staff Auth)
CREATE OR REPLACE FUNCTION public.get_user_id_by_email(email_input TEXT)
RETURNS TABLE (id UUID) AS $$
BEGIN
    RETURN QUERY SELECT p.id FROM public.profiles p WHERE p.email = email_input;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 13. AUTH TRIGGER (Automated Profile Creation)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, phone_number)
  VA
  LUES (
    new.id,
    new.email,
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'phone_number'
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger execution
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 14. REFERRAL TRACKING RPC
CREATE OR REPLACE FUNCTION public.increment_referral_clicks(code_input TEXT)
RETURNS VOID AS $$
BEGIN
    UPDATE public.profiles
    SET referral_clicks = referral_clicks + 1
    WHERE referral_code = code_input;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
