-- APEX OS: MASTER FOUNDATION MIGRATION
-- Evolves the system from a website into an operational machine.

-- 1. SUPPLIERS (Procurement Hub)
CREATE TABLE IF NOT EXISTS public.suppliers (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  bank_details JSONB,
  categories TEXT[] DEFAULT ARRAY[]::TEXT[],
  rating NUMERIC DEFAULT 100.0,
  fill_rate NUMERIC DEFAULT 0.0,
  on_time_dispatch_rate NUMERIC DEFAULT 0.0,
  defect_rate NUMERIC DEFAULT 0.0,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 2. INVENTORY UNITS (Business Memory / Serialized Items)
CREATE TABLE IF NOT EXISTS public.inventory_units (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    supplier_id BIGINT REFERENCES suppliers(id) ON DELETE SET NULL,
    serial_number TEXT UNIQUE,
    imei TEXT UNIQUE,
    cost_price NUMERIC NOT NULL,
    status TEXT DEFAULT 'Available', -- Available, Reserved, Delivered, Returned, Damaged, Lost
    order_id BIGINT REFERENCES public.orders(id) ON DELETE SET NULL,
    received_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 3. ORDER STATE MACHINE (Transition Audit Trail)
CREATE TABLE IF NOT EXISTS public.order_state_history (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
    previous_state TEXT,
    new_state TEXT NOT NULL,
    reason TEXT,
    changed_by TEXT DEFAULT 'system',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 4. FINANCIAL LEDGER (Contribution Profit Tracker)
CREATE TABLE IF NOT EXISTS public.ledger_entries (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
    entry_type TEXT NOT NULL, -- REVENUE, COST, REFUND, ADJUSTMENT
    amount NUMERIC NOT NULL,
    description TEXT,
    is_reconciled BOOLEAN DEFAULT false,
    reconciled_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 5. SUPPORT CASES (Case Management OS)
CREATE TABLE IF NOT EXISTS public.support_cases (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE SET NULL,
    subject TEXT NOT NULL,
    description TEXT NOT NULL,
    priority TEXT DEFAULT 'Medium', -- Low, Medium, High, Critical
    status TEXT DEFAULT 'Open', -- Open, InProgress, WaitingOnCustomer, Resolved, Closed
    assigned_to UUID REFERENCES auth.users(id),
    sla_deadline TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 6. EXCEPTION LOG (Proactive Intelligence Center)
CREATE TABLE IF NOT EXISTS public.exception_log (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    type TEXT NOT NULL, -- PAYMENT_MISMATCH, LOGISTICS_LATENCY, STOCK_RISK, FRAUD_ALERT
    severity TEXT DEFAULT 'Warning', -- Info, Warning, Critical
    details JSONB,
    order_id BIGINT REFERENCES public.orders(id),
    status TEXT DEFAULT 'Open',
    resolved_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 7. TACTICAL FUNCTIONS (State Machine Enforcement)

-- Function to transition order state with audit trail
CREATE OR REPLACE FUNCTION public.transition_order_state(order_id_input BIGINT, new_state_input TEXT, reason_input TEXT, admin_email_input TEXT)
RETURNS VOID AS $$
DECLARE
    current_state TEXT;
BEGIN
    SELECT status INTO current_state FROM public.orders WHERE id = order_id_input;

    -- 1. Logical Validation (The "No Illegal Transitions" Rule)
    -- Example: Cannot go from Delivered to Processing
    IF current_state = 'Delivered' AND new_state_input = 'Processing' THEN
        RAISE EXCEPTION 'Illegal State Transition: % -> %', current_state, new_state_input;
    END IF;

    -- 2. Update Order
    UPDATE public.orders
    SET status = new_state_input, updated_at = NOW()
    WHERE id = order_id_input;

    -- 3. Log History
    INSERT INTO public.order_state_history (order_id, previous_state, new_state, reason, changed_by)
    VALUES (order_id_input, current_state, new_state_input, reason_input, admin_email_input);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 8. AUTO-PROFIT CALCULATION
CREATE OR REPLACE FUNCTION public.calculate_order_profit()
RETURNS trigger AS $$
DECLARE
    product_cost NUMERIC;
BEGIN
    -- 1. Only run when order becomes 'Paid'
    IF NEW.status = 'Paid' AND (OLD.status IS NULL OR OLD.status != 'Paid') THEN
        -- Get average cost if specific unit not linked yet
        SELECT cost_price INTO product_cost FROM public.products WHERE id = NEW.product_id;

        -- Create Revenue Entry
        INSERT INTO public.ledger_entries (order_id, entry_type, amount, description)
        VALUES (NEW.id, 'REVENUE', NEW.total_price, 'Order Revenue');

        -- Create Cost Entry
        INSERT INTO public.ledger_entries (order_id, entry_type, amount, description)
        VALUES (NEW.id, 'COST', -(product_cost * NEW.quantity), 'Inventory Cost');
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS tr_calculate_profit ON public.orders;
CREATE TRIGGER tr_calculate_profit
    AFTER UPDATE ON public.orders
    FOR EACH ROW EXECUTE PROCEDURE public.calculate_order_profit();
