-- APEX OS: SUPPORT & WARRANTY COMMAND CENTER
-- Builds structured resolution machines for high-fidelity after-sales.

-- 1. ENHANCED SUPPORT TICKETS (Case Management)
CREATE TABLE IF NOT EXISTS public.support_tickets (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE SET NULL,
    customer_name TEXT NOT NULL,
    customer_email TEXT NOT NULL,
    subject TEXT NOT NULL,
    description TEXT NOT NULL,
    priority TEXT DEFAULT 'Medium', -- Low, Medium, High, Critical
    category TEXT DEFAULT 'General', -- Technical, Billing, Warranty, Feedback
    status TEXT DEFAULT 'Open', -- Open, InProgress, Resolved, Closed
    assigned_to UUID REFERENCES public.staff(id) ON DELETE SET NULL,
    internal_notes TEXT,
    sla_hours INTEGER DEFAULT 24,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 2. WARRANTY HUB (Reverse Logistics)
CREATE TABLE IF NOT EXISTS public.warranty_cases (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    serial_number TEXT, -- The IMEI/Serial of the unit
    customer_complaint TEXT NOT NULL,
    diagnostic_notes TEXT,
    resolution_type TEXT, -- Repair, Replace, Refund, Rejected
    status TEXT DEFAULT 'Pending_Pickup', -- Pending_Pickup, In_Diagnostic, Repairing, Replacement_Transit, Resolved
    supplier_notified BOOLEAN DEFAULT false,
    supplier_id BIGINT REFERENCES public.suppliers(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 3. AUDIT LOG TRIGGER FOR TICKETS
CREATE OR REPLACE FUNCTION public.log_ticket_change()
RETURNS trigger AS $$
BEGIN
    IF OLD.status != NEW.status THEN
        INSERT INTO public.audit_logs (staff_email, action, details)
        VALUES (
            current_setting('request.jwt.claims', true)::json->>'email',
            'TICKET_STATUS_CHANGE',
            jsonb_build_object('id', NEW.id, 'old', OLD.status, 'new', NEW.status)
        );
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tr_log_ticket_change ON public.support_tickets;
CREATE TRIGGER tr_log_ticket_change
    AFTER UPDATE ON public.support_tickets
    FOR EACH ROW EXECUTE PROCEDURE public.log_ticket_change();
