-- APEX OS: COMPLETE ARCHITECTURAL UPGRADE
-- This migration builds the core machine for proactive operations.

-- 1. EXTENDED SUPPLIERS
CREATE TABLE IF NOT EXISTS public.suppliers (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  email TEXT UNIQUE,
  phone TEXT,
  bank_details JSONB,
  categories TEXT[] DEFAULT ARRAY[]::TEXT[],
  rating NUMERIC DEFAULT 100.0,
  fill_rate NUMERIC DEFAULT 0.0,
  on_time_dispatch_rate NUMERIC DEFAULT 0.0,
  defect_rate NUMERIC DEFAULT 0.0,
  is_active BOOLEAN DEFAULT true,
  lead_time_days INTEGER DEFAULT 1,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 2. SERIALIZED INVENTORY (The IMEI Moat)
CREATE TABLE IF NOT EXISTS public.inventory_units (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    supplier_id BIGINT REFERENCES suppliers(id) ON DELETE SET NULL,
    serial_number TEXT UNIQUE,
    imei TEXT UNIQUE,
    cost_price NUMERIC NOT NULL,
    status TEXT DEFAULT 'Available', -- Available, Reserved, Delivered, Returned, Damaged, Lost
    order_id BIGINT, -- Linked on packing
    received_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 3. MULTI-ITEM ORDERS REFACTOR (Header)
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS total_cost NUMERIC DEFAULT 0;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS fees_paid NUMERIC DEFAULT 0;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS delivery_cost NUMERIC DEFAULT 0;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS risk_score INTEGER DEFAULT 0;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS transition_reason TEXT;

-- 4. ORDER ITEMS (The Granular Truth)
CREATE TABLE IF NOT EXISTS public.order_items (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id),
    inventory_unit_id BIGINT REFERENCES inventory_units(id), -- Specific IMEI linked here
    quantity INTEGER DEFAULT 1,
    unit_price NUMERIC NOT NULL,
    unit_cost NUMERIC NOT NULL,
    supplier_id BIGINT REFERENCES suppliers(id),
    status TEXT DEFAULT 'Pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 5. THE LEDGER (Financial Fortress)
CREATE TABLE IF NOT EXISTS public.financial_ledger (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
    entry_type TEXT NOT NULL, -- REVENUE, SUPPLIER_PAYABLE, DELIVERY_FEE, PAYMENT_FEE, REFUND
    amount NUMERIC NOT NULL,
    description TEXT,
    is_reconciled BOOLEAN DEFAULT false,
    reconciliation_ref TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 6. EXCEPTION CENTER (Red Circle Hub)
CREATE TABLE IF NOT EXISTS public.exception_center (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    exception_code TEXT NOT NULL, -- PM_01 (Payment Mismatch), LD_01 (Logistics Delay), etc.
    type TEXT NOT NULL, -- FINANCE, LOGISTICS, INVENTORY, RISK
    severity TEXT DEFAULT 'Warning',
    title TEXT NOT NULL,
    description TEXT,
    order_id BIGINT REFERENCES public.orders(id),
    status TEXT DEFAULT 'Open', -- Open, InProgress, Resolved
    owner_role TEXT, -- Which admin role should fix this
    deadline TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    resolved_at TIMESTAMP WITH TIME ZONE
);

-- 7. CUSTOMER CRM INTELLIGENCE
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS segment TEXT DEFAULT 'New';
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS lifetime_value NUMERIC DEFAULT 0;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS total_orders INTEGER DEFAULT 0;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS last_purchase_at TIMESTAMP WITH TIME ZONE;

-- 8. TACTICAL STATE MACHINE FUNCTIONS

-- Enforce valid transitions
CREATE OR REPLACE FUNCTION public.check_order_transition()
RETURNS trigger AS $$
BEGIN
    -- Delivered cannot go back to Processing
    IF OLD.status = 'Delivered' AND NEW.status = 'Processing' THEN
        RAISE EXCEPTION 'Apex OS Protocol Violation: Cannot revert delivered mission to processing.';
    END IF;

    -- Update order cost and profit triggers here...

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tr_order_state_machine ON public.orders;
CREATE TRIGGER tr_order_state_machine
    BEFORE UPDATE ON public.orders
    FOR EACH ROW EXECUTE PROCEDURE public.check_order_transition();

-- 9. CONTRIBUTION PROFIT AUTOMATION
CREATE OR REPLACE FUNCTION public.calculate_contribution_profit()
RETURNS trigger AS $$
BEGIN
    IF NEW.status = 'Paid' AND OLD.status != 'Paid' THEN
        -- Automated Ledger Entries
        -- 1. Revenue
        INSERT INTO public.financial_ledger (order_id, entry_type, amount, description)
        VALUES (NEW.id, 'REVENUE', NEW.total_price, 'Customer Payment Received');

        -- 2. Fees (Estimated 3% for Paystack)
        INSERT INTO public.financial_ledger (order_id, entry_type, amount, description)
        VALUES (NEW.id, 'PAYMENT_FEE', -(NEW.total_price * 0.03), 'Payment Gateway Charge');
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tr_contribution_profit ON public.orders;
CREATE TRIGGER tr_contribution_profit
    AFTER UPDATE ON public.orders
    FOR EACH ROW EXECUTE PROCEDURE public.calculate_contribution_profit();
