-- APEX OS: INTELLIGENT RIDER DISPATCH & MISSION TRACKING
-- Upgrades logistics to a high-fidelity fleet command system.

-- 1. ENHANCE RIDER TELEMETRY
ALTER TABLE public.rider_status
ADD COLUMN IF NOT EXISTS lat NUMERIC,
ADD COLUMN IF NOT EXISTS lng NUMERIC,
ADD COLUMN IF NOT EXISTS speed NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS heading NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS accuracy NUMERIC,
ADD COLUMN IF NOT EXISTS current_order_id BIGINT,
ADD COLUMN IF NOT EXISTS reliability_score NUMERIC DEFAULT 100, -- 0-100
ADD COLUMN IF NOT EXISTS avg_extraction_time INTEGER; -- In minutes

-- 2. ENHANCE ORDER ROUTING
ALTER TABLE public.orders
ADD COLUMN IF NOT EXISTS pickup_lat NUMERIC,
ADD COLUMN IF NOT EXISTS pickup_lng NUMERIC,
ADD COLUMN IF NOT EXISTS route_geometry TEXT, -- Encoded polyline
ADD COLUMN IF NOT EXISTS estimated_arrival TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS actual_arrival TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS mission_status TEXT DEFAULT 'Pending'; -- 'Draft', 'Active', 'Arrived', 'Completed'

-- 3. RIDER TELEMETRY LOG (High-frequency storage)
CREATE TABLE IF NOT EXISTS public.rider_telemetry_log (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    rider_phone TEXT REFERENCES public.rider_status(rider_phone) ON DELETE CASCADE,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE SET NULL,
    lat NUMERIC NOT NULL,
    lng NUMERIC NOT NULL,
    speed NUMERIC,
    heading NUMERIC,
    captured_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_telemetry_rider_time ON public.rider_telemetry_log(rider_phone, captured_at DESC);

-- 4. FLEET EXCEPTIONS (Anomaly Detection)
CREATE TABLE IF NOT EXISTS public.fleet_exceptions (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    type TEXT NOT NULL, -- 'STALL', 'DEVIATION', 'ETA_BREACH', 'GPS_LOSS'
    severity TEXT DEFAULT 'Warning',
    rider_phone TEXT REFERENCES public.rider_status(rider_phone),
    order_id BIGINT REFERENCES public.orders(id),
    description TEXT,
    is_resolved BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 5. RLS & PERMISSIONS
ALTER TABLE public.rider_telemetry_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fleet_exceptions ENABLE ROW LEVEL SECURITY;

-- Admins see all logs
CREATE POLICY "Admins manage telemetry" ON public.rider_telemetry_log FOR ALL TO authenticated USING (true);
CREATE POLICY "Admins manage exceptions" ON public.fleet_exceptions FOR ALL TO authenticated USING (true);

-- Riders only insert their own telemetry
CREATE POLICY "Riders insert telemetry" ON public.rider_telemetry_log
FOR INSERT WITH CHECK (true); -- Simplified for now, refine with JWT phone check later

-- 6. FUNCTIONS

-- Update reliability score based on completion
CREATE OR REPLACE FUNCTION public.update_rider_reliability(phone_input TEXT, impact_score NUMERIC)
RETURNS VOID AS $$
BEGIN
    UPDATE public.rider_status
    SET reliability_score = GREATEST(0, LEAST(100, reliability_score + impact_score))
    WHERE rider_phone = phone_input;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
